"""new comment fields in user model

Revision ID: 421eacdf8d02
Revises: 3d6fdfd468f8
Create Date: 2024-05-03 02:43:52.221176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421eacdf8d02'
down_revision = '3d6fdfd468f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
